### ISSUE TITLE
一点问题请教

### ISSUE THREAD

**Issue by xiaxiaxiaxia** [SubDragonzj/android_device_xiaomi_rosy#1]
子龙你好，我想用你开放出来的三件套尝试一下编译的感觉，但是编译到百分之70几的时候就报了这个错误，三件套和魔趣的都是一样的呀，是什么原因呢

device/xiaomi/rosy/doze/res/values/styles.xml:34: error: resource layout/preference_category_material_settings (aka org.mokee.settings.doze:layout/preference_category_material_settings) not found.
device/xiaomi/rosy/doze/res/values/styles.xml:45: error: resource layout/preference_material_settings (aka org.mokee.settings.doze:layout/preference_material_settings) not found.
error: failed linking references.
[ 72% 69894/96760] target R.java/Manifest.java:...obj/APPS/TeleService_intermediates/src/R.stamp)
ninja: build stopped: subcommand failed.
20:23:32 ninja failed with: exit status 1

**Comment by SubDragonzj** [comment]
https://github.com/MoKee/android_device_xiaomi_rosy/blob/mkp/device.mk#L87
